Repository o1-labs/zkapp-cli, pull requests merged in 2024-02, with the labels that each got.

#564 Add support for mainnet.
  .husky/_/husky.sh
  CHANGELOG.md
  package-lock.json
  package.json
  src/lib/config.js
  src/lib/constants.js
  src/lib/deploy.js
  src/lib/prompts.js
  templates/project-ts/package.json
  templates/project-ts/src/interact.ts
  tests/cli/config.spec.ts
  tests/cli/deploy.spec.ts
  tests/cli/interact.spec.ts
  tests/models/types.ts
  tests/utils/common-utils.ts
  tests/utils/config-utils.ts
  tests/utils/deploy-utils.ts
Labels: berkeley-mainnet

#577 Allow to use locally available Explorer in case of no network.
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/bin/index.js
  src/lib/lightnet.js
  templates/project-ts/package.json
Labels: lightnet

#580 Feepayer permissions error handling
  CHANGELOG.md
  src/lib/deploy.js
Labels: error-handling

#581 Update cached feepayer logic
  CHANGELOG.md
  src/lib/config.js
Labels: error-handling

#579 Automate 'zk config' if Lightnet is in use.
  CHANGELOG.md
  package-lock.json
  package.json
  src/bin/index.js
  src/lib/config.js
  src/lib/constants.js
  src/lib/deploy.js
  src/lib/example.js
  src/lib/file.js
  src/lib/helpers.js
  src/lib/lightnet.js
  src/lib/project.js
  tests/cli/config.spec.ts
  tests/cli/deploy.spec.ts
Labels: lightnet

#586 Improve error handling when smart contract is not found
  CHANGELOG.md
  src/lib/deploy.js
Labels: error-handling

#591 Improve CLI errors handling.
  CHANGELOG.md
  src/bin/index.js
Labels: bug
